name: Build and Deploy Jekyll to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install Jekyll
        run: |
          gem install jekyll

      - name: Build Jekyll site with PostHog key
        env:
          POSTHOG_KEY: ${{ secrets.POSTHOG_KEY }}
        run: |
          jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
